use_default_settings: true

server:
  secret_key: 'd81f476f29e5a6ff74c45868d26f19f3bca7e9994ca5c69c94d3627c7733cc46'
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ''
  default_lang: ''
  formats:
    - html
    - json # 필수: API 사용을 위해 JSON 포맷 활성화

engines:
  - name: brave
    disabled: true # CAPTCHA 문제 방지
  - name: qwant
    disabled: true # CAPTCHA 문제 방지
